# Example configuration.yaml entry
smart_mini_split:
  entity_id: climate.minisplit
  external_sensor: sensor.awair_element_110243_temperature
  valid_range: [64, 74]
  adjustment_step: 10
  trigger_threshold: 2
  reset_threshold: 1
  cooldown_minutes: 5
  log_level: info  # or debug
