force_adjustment:
  name: Force Adjustment
  description: Force an immediate temperature check and adjustment
  fields: {}

toggle_automation:
  name: Toggle Automation
  description: Enable or disable the smart mini split automation
  fields:
    enabled:
      name: Enabled
      description: Whether to enable or disable the automation
      required: true
      selector:
        boolean: {}

clear_override:
  name: Clear Override
  description: Clear any manual override flags
  fields: {}
